services:
  frontend:
    build: .
    container_name: solid_data_manager_frontend
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    stdin_open: true
    environment:
      - REACT_APP_OIDC_ISSUER=https://solidcommunity.net
      - REACT_APP_REDIRECT_URL=${REACT_APP_REDIRECT_URL:-http://localhost}
      - REACT_APP_FOOTER_LOGOS=/Logo_TMDT.png
      - REACT_APP_VERSION=0.1.0
      - PORT=3002
    tty: true
    ports:
      - "${FRONTEND_PORT:-3002}:3002"
